### ISSUE TITLE
New module related issues when upgrading

### ISSUE THREAD

**Issue by eikeon** [117/alpaca#50] opened 2021-02-07 02:53 UTC
**Description**

Upgrading from  @master-chief/alpaca  ^3.6.3  →  ^4.2.3     

I've just begin to dig on these to... but in case they are some other quick ones. Both of these are new for me (the cdk synth one involves bundling with esbuild):

```
eikeon@iMac matic % npm run build

> matic@0.1.6 build /Users/eikeon/matic
> tsc

eikeon@iMac matic % npm run cdk synth

> matic@0.1.6 cdk /Users/eikeon/matic
> cdk "synth"

Bundling asset MaticPipeline/PreProd/Matic/handler/Code/Stage...
 > ../node_modules/node-gyp-build/index.js: warning: Indirect calls to "require" will not be bundled (surround with a try/catch to silence this warning)
    6 │ var runtimeRequire = typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require // eslint-disable-line
      ╵                                                                                            ~~~~~~~

1 warning
Successfully synthesized to /Users/eikeon/matic/cdk.out
Supply a stack id (MaticPipeline, MaticRepo) to display its template.
eikeon@iMac matic % node_modules/.bin/ts-node t.ts                                                                                                                                             
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/eikeon/matic/node_modules/@master-chief/alpaca/dist/mjs/index.js
require() of ES modules is not supported.
require() of /Users/eikeon/matic/node_modules/@master-chief/alpaca/dist/mjs/index.js from /Users/eikeon/matic/lib/matic-stack-handler.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/eikeon/matic/node_modules/@master-chief/alpaca/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/eikeon/matic/lib/matic-stack-handler.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
eikeon@iMac matic % 

```

**Comment by 117** [comment] 2021-02-07 03:01
The fix for this would be to add back native support for commonjs. Which we ditched in version `4.0.0`. Not sure if we should add it back 😕. I personally use ESNext in all my projects.. but that doesn't mean others aren't still using commonjs en masse.

**Comment by 117** [comment] 2021-02-07 03:05
@husayt any thoughts on this?

**Comment by eikeon** [comment] 2021-02-07 03:37
I'm targeting node v14 if there's a way I can update my tsconfig.json and esbuild related config. Digging to see what value of platform I'm using with esbuild and if it always converts to CommonJS: https://esbuild.github.io/getting-started/#bundling-for-node

**Comment by 117** [comment] 2021-02-07 04:33
I got it to work with the following `tsconfig.json`.
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "noEmit": true,
    "strict": true,
    "lib": ["es2020"]
  }
}
```
Then running with the following command.
```
node --loader ts-node/esm index.ts
```
Any success on your end?

**Comment by husayt** [comment] 2021-02-07 14:04
It's very difficult to say without reproduction. Often, issue is not where error message points too. In example folder  provided multiple ways of using the library. If there is an issue, would be great to resolve, but we need to make sure that the problem is on our side first. @eikeon can you please provide a mini example ?

**Comment by eikeon** [comment] 2021-02-07 14:27
@husayt I ran out of time yesterday trying to track down my issue -- perhaps one of my other dependencies is forcing me into CommonJS land -- when I get a chance later today I'll trim down or build up to see if I can isolate the issue. @117, I was able to reproduce that example working locally --  hopefully it'll help me figure out why not with my own module in the middle

**Comment by eikeon** [comment] 2021-02-07 15:50
Think at this stage my issues are related to changing my tsconfig.json compilerOption module from commonjs to esnext. If I add a .js to my import like describe here: https://dev.to/eiymba/compiling-typescript-to-esnext-for-back-end-node-js-apps-190l#typescript-compiler-options — it starts to work; although I’m not sure that’s the right way to go about it... still reading. Any pointers would be welcome re: good doc to read for the intersection of Typescript and module esnext and node — think  https://www.typescriptlang.org/docs/handbook/modules.html is only one of the pieces looking to revisit the relevant parts of Node’s documentation.

I’ll open a new ticket if I find any issues with alpaca — perhaps this issue can be reduced to having the README point out that “native support for commonjs” is no longer supported 

@117 and @husayt, thank you for the help!

**Comment by eikeon** [comment] 2021-02-07 15:58
>  So all in all this can be summarized as: Using TypeScript, node.js and the TypeScript compiler option "module": "esnext" together is next to impossible.
— https://www.tsmean.com/articles/learn-typescript/typescript-module-compiler-option/

Feels a bit better that it’s not just me ;)

**Comment by eikeon** [comment] 2021-02-07 16:03
> So if you're building code that should be ran with node.js, in 2020, you should still choose "module": "commonjs".

> If you're building code that is to be used by browsers, things are different. Browsers don't have the slightest clue about CommonJs modules, but all modern browsers on the other hand now do support ES modules. If you want to target older browsers (looking at you, Internet Explorer), you will probably want to bundle your code together, which can be done for example by Webpack.

Has enough changed in 2021 to drop commonjs re: supporting the case for those targeting node? But perhaps doing so will help bring on that change ;)

**Comment by husayt** [comment] 2021-02-07 16:08
@eikeon since node 14 (current LTE) supports es modules, there was no much point to cling to commonjs.  Besides, that allowed us to properly support browsers and other combinations:
Cuurently these bundles are provided:

* alpaca.js - ESM bundle (for node)
* alpaca.bundle.js - ESM bundle with dependencies (for node)
* alpaca.browser.js - UMD bundle (for browser)
* alpaca.browser.modern.js - ESM modern bundle (for browser)

**Comment by eikeon** [comment] 2021-02-07 16:14
/me bookmarks https://github.com/TypeStrong/ts-node/issues/1007 Re: working with TS and ESM — I rather not cling so happy to make the transition

**Comment by eikeon** [comment] 2021-02-07 18:45
I'm following the recommendations from:

    https://github.com/tsconfig/bases#node-14-tsconfigjson

And it sounds like ESM with TS and node:14 is not quite there yet by:

    https://github.com/tsconfig/bases/issues/2

So guess I can revert to v3.6.3 until I figure out which direction to go in.

That said; It does look like I can get all working with https://www.npmjs.com/package/esm in the mix

**Comment by 117** [comment] 2021-02-07 19:15
Looking into how difficult simply adding another build step for commonjs would be. It _shouldn't_ break anything else.

**Comment by husayt** [comment] 2021-02-07 19:29
@117 you can give it a try, but it will be painful.  I have a project working just fine with the setup above. 

What would be really useful is an example reproduction of the problem. Then we could get to the bottom of it.

**Comment by 117** [comment] 2021-02-07 19:29
@eikeon Hey can you test the #staging branch and see if it works with your current build setup? 

`npm i 117/alpaca#staging`

**Comment by 117** [comment] 2021-02-07 19:32
> @117 you can give it a try, but it will be painful. I have a project working just fine with the setup above.
> 
> What would be really useful is an example reproduction of the problem. Then we could get to the bottom of it.

I experienced the issue he was facing when trying to use the same compiler. Without taking extra steps new users of `ts-node` will hit the same wall. While there is a way around it, its actually more complicated than just adding `cjs` compilation for legacy support on our end. The JS community really hasn't progressed enough to ditch it entirely IMO.

**Comment by husayt** [comment] 2021-02-07 19:40
Of course, if all that can be supported without major compromises that is great. The issue for me was enabling one was breaking the other. Maybe I was missing something.

**Comment by eikeon** [comment] 2021-02-07 21:32
> npm i 117/alpaca#staging

That works to run my test and all is happy there.

Not sure if it's making it through esbuild or not -- I'm seeing this when it goes through

```
npm run cdk synth               

> matic@0.1.6 cdk /Users/eikeon/matic
> cdk "synth"

Bundling asset MaticPipeline/PreProd/Matic/handler/Code/Stage...
 > ../node_modules/node-gyp-build/index.js: warning: Indirect calls to "require" will not be bundled (surround with a try/catch to silence this warning)
    6 │ var runtimeRequire = typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require // eslint-disable-line
      ╵                                                                                            ~~~~~~~

1 warning
Successfully synthesized to /Users/eikeon/matic/cdk.out
```

**Comment by 117** [comment] 2021-02-07 22:24
I'm gonna mark this as solved for now and do some further testing. Expect an NPM version to be pushed soon if I don't find any conflicts. :)

**Closed by 117** 2021-02-07 22:24 UTC
Labels: bug

**Comment by eikeon** [comment] 2021-02-08 00:15
@117 Thank you! -- I was able to verify that it works even with that warning as well. Also, I added it to `nodeModules` A list of modules that should be installed instead of bundled -- that I have available as an option that's kicking off the bundling. And hopefully with the combination of tools I'm using ESM will be a recommended option soon to leave some of this complexity behind
